### ISSUE TITLE
httpclient example fatal error - unexpected fault address

### ISSUE THREAD

**Issue by aymanbagabas** [zzl/go-winrtapi#1]
Running the httpclient example fail

```
PS C:\Users\Ayman\Sources\go-winrtapi\examples\httpclient> go run .
13028
13028
unexpected fault address 0x21c00000000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x21c00000000 pc=0x8780d4]

goroutine 1 [running, locked to thread]:
runtime.throw({0x89c977?, 0xc000074720?})
        C:/Program Files/Go/src/runtime/panic.go:992 +0x76 fp=0xc00007d700 sp=0xc00007d6d0 pc=0x8036d6
runtime.sigpanic()
        C:/Program Files/Go/src/runtime/signal_windows.go:261 +0x125 fp=0xc00007d748 sp=0xc00007d700 pc=0x814e05
github.com/zzl/go-winrtapi/winrt.(*IAsyncOperationWithProgress[...]).Vtbl(...)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/Foundation.go:333
github.com/zzl/go-winrtapi/winrt.(*IAsyncOperationWithProgress[...]).GetResults(0xc00007d7c0)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/Foundation.go:362 +0x34 fp=0xc00007d7a0 sp=0xc00007d748 pc=0x8780d4
main.main.func2(0x877385?, 0x7e172c?)
        C:/Users/Ayman/Sources/go-winrtapi/examples/httpclient/httpclient.go:28 +0x25 fp=0xc00007d7d8 sp=0xc00007d7a0 pc=0x878e65
github.com/zzl/go-winrtapi/winrt.NewTwoArgFuncDelegate[...].func1(0x892f60?, 0x82e800?)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/1_delegate.go:137 +0x42 fp=0xc00007d808 sp=0xc00007d7d8 pc=0x878fc2
github.com/zzl/go-winrtapi/winrt.(*IDelegateByFuncImpl).Invoke(0xc00007db70?, 0xc00007d870?, 0x82962b?, 0x0?)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/1_delegate.go:109 +0x26 fp=0xc00007d830 sp=0xc00007d808 pc=0x877826
github.com/zzl/go-winrtapi/winrt.(*IDelegateComObj).Invoke(0xc00007d8a0?, 0x82a9bd?, 0x7dc405?, 0xc00007d910?)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/1_delegate.go:62 +0x79 fp=0xc00007d880 sp=0xc00007d830 pc=0x877459
runtime.call32(0x0, 0x8a7ef0, 0xc00007d918, 0x0, 0x0, 0x20, 0xc00007db70)
        C:/Program Files/Go/src/runtime/asm_amd64.s:702 +0x50 fp=0xc00007d8b0 sp=0xc00007d880 pc=0x82aa50
runtime.callbackWrap(0x51a85ff410)
        C:/Program Files/Go/src/runtime/syscall_windows.go:378 +0x134 fp=0xc00007dc90 sp=0xc00007d8b0 pc=0x81cf54
runtime.cgocallbackg1(0x81ce20, 0xc00007de50?, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:314 +0x2ca fp=0xc00007dd60 sp=0xc00007dc90 pc=0x7d39ea
runtime.cgocallbackg(0xc00003e000?, 0x300000002?, 0xc00003e000?)
        C:/Program Files/Go/src/runtime/cgocall.go:233 +0x106 fp=0xc00007ddf8 sp=0xc00007dd60 pc=0x7d3626
runtime.cgocallbackg(0x81ce20, 0x51a85ff410, 0x0)
        <autogenerated>:1 +0x36 fp=0xc00007de20 sp=0xc00007ddf8 pc=0x82e6f6
runtime.cgocallback(0x7d34ab, 0x82e000, 0x9529e0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:971 +0xd7 fp=0xc00007de48 sp=0xc00007de20 pc=0x82c557
runtime.systemstack_switch()
        C:/Program Files/Go/src/runtime/asm_amd64.s:436 fp=0xc00007de50 sp=0xc00007de48 pc=0x82a440
runtime.cgocall(0x82e000, 0x9529e0)
        C:/Program Files/Go/src/runtime/cgocall.go:167 +0xab fp=0xc00007de88 sp=0xc00007de50 pc=0x7d34ab
syscall.SyscallN(0x7ffaa7dc5790?, {0xc000012240?, 0x2?, 0xc00007df10?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109 fp=0xc00007df00 sp=0xc00007de88 pc=0x829509
github.com/zzl/go-winrtapi/winrt.(*IAsyncOperationWithProgress[...]).Put_Completed(0x21cc1b0bf90, 0x0)
        C:/Users/Ayman/Sources/go-winrtapi/winrt/Foundation.go:349 +0x85 fp=0xc00007df48 sp=0xc00007df00 pc=0x878065
main.main()
        C:/Users/Ayman/Sources/go-winrtapi/examples/httpclient/httpclient.go:26 +0x85 fp=0xc00007df80 sp=0xc00007df48 pc=0x878f65
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1fe fp=0xc00007dfe0 sp=0xc00007df80 pc=0x805cde
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x82c7a1
exit status 2
```

**Comment by zzl** [comment]
My apologies for the delayed response, one year later...
This issue should have been fixed in the latest version.
